package com.example.compose
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF9724b7)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFfed6ff)
val md_theme_light_onPrimaryContainer = Color(0xFF340044)
val md_theme_light_secondary = Color(0xFF6a596c)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf3dbf3)
val md_theme_light_onSecondaryContainer = Color(0xFF241727)
val md_theme_light_tertiary = Color(0xFF82524d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdad4)
val md_theme_light_onTertiaryContainer = Color(0xFF33110e)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1e1a1e)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1e1a1e)
val md_theme_light_surfaceVariant = Color(0xFFecdfe9)
val md_theme_light_onSurfaceVariant = Color(0xFF4d444d)
val md_theme_light_outline = Color(0xFF7e747d)
val md_theme_light_inverseOnSurface = Color(0xFFf7eef3)
val md_theme_light_inverseSurface = Color(0xFF332f33)
val md_theme_light_inversePrimary = Color(0xFFf4adff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFf4adff)
val md_theme_dark_onPrimary = Color(0xFF55006d)
val md_theme_dark_primaryContainer = Color(0xFF780099)
val md_theme_dark_onPrimaryContainer = Color(0xFFfed6ff)
val md_theme_dark_secondary = Color(0xFFd6c0d6)
val md_theme_dark_onSecondary = Color(0xFF3a2b3c)
val md_theme_dark_secondaryContainer = Color(0xFF524154)
val md_theme_dark_onSecondaryContainer = Color(0xFFf3dbf3)
val md_theme_dark_tertiary = Color(0xFFf5b8b1)
val md_theme_dark_onTertiary = Color(0xFF4c2522)
val md_theme_dark_tertiaryContainer = Color(0xFF673b36)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdad4)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1e1a1e)
val md_theme_dark_onBackground = Color(0xFFe8e0e4)
val md_theme_dark_surface = Color(0xFF1e1a1e)
val md_theme_dark_onSurface = Color(0xFFe8e0e4)
val md_theme_dark_surfaceVariant = Color(0xFF4d444d)
val md_theme_dark_onSurfaceVariant = Color(0xFFcfc3cd)
val md_theme_dark_outline = Color(0xFF988d97)
val md_theme_dark_inverseOnSurface = Color(0xFF1e1a1e)
val md_theme_dark_inverseSurface = Color(0xFFe8e0e4)
val md_theme_dark_inversePrimary = Color(0xFF9724b7)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFFa332c3)
val error = Color(0xFFba1b1b)